# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import ai_decision_pb2 as ai__decision__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ai_decision_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AiDecisionServiceStub(object):
    """The service exposed by the external AI (e.g., Python Inference Server)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetDecision = channel.unary_unary(
                '/forge.proto.AiDecisionService/GetDecision',
                request_serializer=ai__decision__pb2.DecisionRequest.SerializeToString,
                response_deserializer=ai__decision__pb2.DecisionResponse.FromString,
                _registered_method=True)


class AiDecisionServiceServicer(object):
    """The service exposed by the external AI (e.g., Python Inference Server)
    """

    def GetDecision(self, request, context):
        """Forge calls this to get a decision from the AI
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AiDecisionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetDecision': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDecision,
                    request_deserializer=ai__decision__pb2.DecisionRequest.FromString,
                    response_serializer=ai__decision__pb2.DecisionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'forge.proto.AiDecisionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('forge.proto.AiDecisionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AiDecisionService(object):
    """The service exposed by the external AI (e.g., Python Inference Server)
    """

    @staticmethod
    def GetDecision(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forge.proto.AiDecisionService/GetDecision',
            ai__decision__pb2.DecisionRequest.SerializeToString,
            ai__decision__pb2.DecisionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
