# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ai_decision.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ai_decision.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import mtg_state_pb2 as mtg__state__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x61i_decision.proto\x12\x0b\x66orge.proto\x1a\x0fmtg_state.proto\"=\n\x0f\x44\x65\x63isionRequest\x12*\n\ngame_state\x18\x01 \x01(\x0b\x32\x16.forge.proto.GameState\"%\n\x10\x44\x65\x63isionResponse\x12\x11\n\taction_id\x18\x01 \x01(\t2_\n\x11\x41iDecisionService\x12J\n\x0bGetDecision\x12\x1c.forge.proto.DecisionRequest\x1a\x1d.forge.proto.DecisionResponseB \n\x0b\x66orge.protoB\x0f\x41iDecisionProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai_decision_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013forge.protoB\017AiDecisionProtoP\001'
  _globals['_DECISIONREQUEST']._serialized_start=51
  _globals['_DECISIONREQUEST']._serialized_end=112
  _globals['_DECISIONRESPONSE']._serialized_start=114
  _globals['_DECISIONRESPONSE']._serialized_end=151
  _globals['_AIDECISIONSERVICE']._serialized_start=153
  _globals['_AIDECISIONSERVICE']._serialized_end=248
# @@protoc_insertion_point(module_scope)
