# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: simulation.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'simulation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10simulation.proto\x12\x0b\x66orge.proto\"\xc7\x01\n\x11SimulationRequest\x12\x12\n\ndeck1_path\x18\x01 \x01(\t\x12\x12\n\ndeck2_path\x18\x02 \x01(\t\x12\x13\n\x0bnum_matches\x18\x03 \x01(\x05\x12)\n\nplayer1_ai\x18\x04 \x01(\x0b\x32\x15.forge.proto.AiConfig\x12)\n\nplayer2_ai\x18\x05 \x01(\x0b\x32\x15.forge.proto.AiConfig\x12\x1f\n\x17\x65nable_decision_logging\x18\x06 \x01(\x08\"p\n\x08\x41iConfig\x12*\n\x04type\x18\x01 \x01(\x0e\x32\x1c.forge.proto.AiConfig.AiType\x12\x15\n\rgrpc_endpoint\x18\x02 \x01(\t\"!\n\x06\x41iType\x12\r\n\tHEURISTIC\x10\x00\x12\x08\n\x04GRPC\x10\x01\"?\n\x12SimulationResponse\x12)\n\x07results\x18\x01 \x03(\x0b\x32\x18.forge.proto.MatchResult\"h\n\x0bMatchResult\x12\x10\n\x08match_id\x18\x01 \x01(\t\x12\x13\n\x0bwinner_name\x18\x02 \x01(\t\x12\x11\n\tnum_turns\x18\x03 \x01(\x05\x12\x12\n\nwin_reason\x18\x04 \x01(\t\x12\x0b\n\x03\x64nf\x18\x05 \x01(\x08\x32\xbd\x01\n\x16MatchSimulationService\x12P\n\rRunSimulation\x12\x1e.forge.proto.SimulationRequest\x1a\x1f.forge.proto.SimulationResponse\x12Q\n\x13RunSimulationStream\x12\x1e.forge.proto.SimulationRequest\x1a\x18.forge.proto.MatchResult0\x01\x42 \n\x0b\x66orge.protoB\x0fSimulationProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'simulation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013forge.protoB\017SimulationProtoP\001'
  _globals['_SIMULATIONREQUEST']._serialized_start=34
  _globals['_SIMULATIONREQUEST']._serialized_end=233
  _globals['_AICONFIG']._serialized_start=235
  _globals['_AICONFIG']._serialized_end=347
  _globals['_AICONFIG_AITYPE']._serialized_start=314
  _globals['_AICONFIG_AITYPE']._serialized_end=347
  _globals['_SIMULATIONRESPONSE']._serialized_start=349
  _globals['_SIMULATIONRESPONSE']._serialized_end=412
  _globals['_MATCHRESULT']._serialized_start=414
  _globals['_MATCHRESULT']._serialized_end=518
  _globals['_MATCHSIMULATIONSERVICE']._serialized_start=521
  _globals['_MATCHSIMULATIONSERVICE']._serialized_end=710
# @@protoc_insertion_point(module_scope)
