# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import simulation_pb2 as simulation__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in simulation_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MatchSimulationServiceStub(object):
    """The service exposed by Forge (Headless Server)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RunSimulation = channel.unary_unary(
                '/forge.proto.MatchSimulationService/RunSimulation',
                request_serializer=simulation__pb2.SimulationRequest.SerializeToString,
                response_deserializer=simulation__pb2.SimulationResponse.FromString,
                _registered_method=True)
        self.RunSimulationStream = channel.unary_stream(
                '/forge.proto.MatchSimulationService/RunSimulationStream',
                request_serializer=simulation__pb2.SimulationRequest.SerializeToString,
                response_deserializer=simulation__pb2.MatchResult.FromString,
                _registered_method=True)


class MatchSimulationServiceServicer(object):
    """The service exposed by Forge (Headless Server)
    """

    def RunSimulation(self, request, context):
        """Python/External script calls this to start a batch of simulations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunSimulationStream(self, request, context):
        """Stream results as they come in
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MatchSimulationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RunSimulation': grpc.unary_unary_rpc_method_handler(
                    servicer.RunSimulation,
                    request_deserializer=simulation__pb2.SimulationRequest.FromString,
                    response_serializer=simulation__pb2.SimulationResponse.SerializeToString,
            ),
            'RunSimulationStream': grpc.unary_stream_rpc_method_handler(
                    servicer.RunSimulationStream,
                    request_deserializer=simulation__pb2.SimulationRequest.FromString,
                    response_serializer=simulation__pb2.MatchResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'forge.proto.MatchSimulationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('forge.proto.MatchSimulationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MatchSimulationService(object):
    """The service exposed by Forge (Headless Server)
    """

    @staticmethod
    def RunSimulation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forge.proto.MatchSimulationService/RunSimulation',
            simulation__pb2.SimulationRequest.SerializeToString,
            simulation__pb2.SimulationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunSimulationStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/forge.proto.MatchSimulationService/RunSimulationStream',
            simulation__pb2.SimulationRequest.SerializeToString,
            simulation__pb2.MatchResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
